- name: Task that check if java installed, if not, then installs it
  shell: java -version
  register: java_check
  ignore_errors: true
- name: Output the java version
  debug:
    msg: "The java version that is installed {{ java_check }}"
  when: java_check == 0
- name: Update all apt packages
  become: true
  apt:
    update_cache: yes
  when: java_check != 0 
- name: Output that Java is not installed and install it
  apt: 
    name: openjdk-17-jdk
    state: present
  when: java_check != 0
- name: Register java versions
  shell: java -version
  register: java_version
- name: Print Java version
  debug:
    msg: "Java is installed {{ java_version }}"

