# tasks file for common
- name: Include all tasks of the role common
  include_tasks: "{{ item }}"
  loop:
  - ping-common.yml
#  - check-java-install-common.yml
#  - find-install-path-java.yml
#  - install-confluent.yml 
  - copy-pubkey-ca.yml
